__author__ = "Ida Karlsson"
__copyright__ = "Copyright 2024, Ida Karlsson"
__email__ = "ida.karlsson@scilifelab.uu.se"
__license__ = "GPL-3"


# Include pipeline specific rules
include: "rules/common.smk"


# 'All' rule, must be specified before any other modules are
# included, since they also contain 'All' rule
rule all:
    input:
        compile_output_file_list,


# Include modules
